# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 192680064d96dcc5e6c3e07aa67effd711139ab99bdff82a42e75da953c680d82344fd84fc2726cf4fb119937d0595ed641c363c69ce87d0a2e37538a3ffb0c4

test:
  secret_key_base: 3a7bcd12fbbbea9c5753212db1ffb50e927a10f6f33ea86b4505fe50def5faf3f69c20a8e06e8a1752f1a7f24b8d8b2729c675c93b07918c30fc9d3abaadf713

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
